### ISSUE TITLE
broken JS snippet: unnecessary backslashes + incorrect escaping

### ISSUE THREAD

**Issue by gregsadetsky** [mixpanel/docs-legacy#151]
on https://docs.mixpanel.com/docs/tracking/javascript-quickstart

the JavaScript snippet appears like this:

<img width="356" alt="image" src="https://github.com/mixpanel/docs/assets/1017304/0af7c9a3-0903-4d5f-b70b-da5d3e813e54">

the backslashes (around text/javascript) are not necessary -- they probably appear on the page by mistake. the snippet should start in the following way:

```html
<script type="text/javascript">
```

note also that there are `\n` characters that appear in the snippet -- they are also not necessary/valid.

... and I also see now that `d.split(\".\");` for instance in the snippet is incorrect, as those quote signs should not be escaped... thinking of it now, that whole snippet is incorrect..!

**Comment by hesamjs** [comment]
Also another issue with js script:
an unescaped regex is throwing "Uncaught SyntaxError: missing ) after argument list" error here:

`&& "//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^///)`
