### ISSUE TITLE
Identifying Users confusion

### ISSUE THREAD

**Issue by julianneb-mixpanel** [mixpanel/docs-legacy#173]
Hi all! I recently got two tickets around ID management where there was confusion due to the docs. I think that the new doc is confusing since it tries to lump together Simplified and Original. It would be great to fully separate the two options since they are different in key ways. Some examples of potential confusion with the lumping together:

- Usage mentions calling identify() but doesn't specify that is for Original. [One ticket ](https://mixpanelsupport.zendesk.com/agent/tickets/504586)was about not being sure how to set up with simplified
- Example User Flow also has 'identify() in New User Signup, but doesn't say to call it in the Returning User or Multiple Users, One Device sections
- The Example User Flow shows the distinct_id (set by Mixpanel) as being set to the User ID. This is only true for Simplified. [This ticket](https://mixpanelsupport.zendesk.com/agent/tickets/504700) was from a user who thought the canonical ID would be the user ID on Original as well.
- FAQ says "you cannot merge 2 $user_ids or change a $user_id, so if the user changes their email, they will count as a separate user." Which is only true for Simplified. And then later has a Q of "Is it possible to merge two $user_ids // If you are on Original ID Merge, we do have a $merge API call that can merge two $user_ids.

**Comment by emmajaniszewski1** [comment]
Couldn't agree more - seeing a bunch of confusion relating to ID management as a whole, where users on original ID Merge are trying to use the (seemingly default) methods of simplified ID Merge. This then creates a feedback loop of negativity because simplified cannot be enabled on projects with existing data.

**Comment by julianneb-mixpanel** [comment]
Hey @ranic ! I don't think the move to simplified API being the default resolves this issue. There is still inconsistent info and missing info that is listed above.

For the [Merge question](https://docs.mixpanel.com/docs/tracking/how-tos/identifying-users#is-it-possible-to-merge-two-user_ids), the FAQ doesn't give an answer (possible on Original but not simplified)
