### ISSUE TITLE
Duplication of images

### ISSUE THREAD

**Issue by logueslinccl** [mixpanel/docs-legacy#218]
The example images are duplicated throughout.

**Comment by ranic** [comment]
👋  mind providing a bit more detail about the page you were referring to?

**Comment by logueslinccl** [comment]
The example images shown on this doc: https://docs.mixpanel.com/docs/analysis/advanced/custom-properties
 are repeated several times.

**Comment by ranic** [comment]
Should be fixed here: https://github.com/mixpanel/docs/commit/99d7e3a26ba0c95fc0dc5dec2f9e0a946154f3ed

Thank you for spotting this -- let us know if there are other issues!
