### ISSUE TITLE
Docs>Retention page: Image does not match text description

### ISSUE THREAD

**Issue by ylevtov** [mixpanel/docs-legacy#243]
https://github.com/mixpanel/docs/blob/1a91aa665d7b97d6d8aa85d5b4184726e499556d/pages/docs/analysis/how-tos/retention.md?plain=1#L28

**Comment by ylevtov** [comment]
In fact I'm not sure many of the images on this page match up with the text...

**Comment by ranic** [comment]
Same resolution as https://github.com/mixpanel/docs/issues/250
