### ISSUE TITLE
Incomplete sentence in Docs>Retention

### ISSUE THREAD

**Issue by ylevtov** [mixpanel/docs-legacy#244]
https://github.com/mixpanel/docs/blob/1a91aa665d7b97d6d8aa85d5b4184726e499556d/pages/docs/analysis/how-tos/retention.md?plain=1#L32

**Comment by ranic** [comment]
https://github.com/mixpanel/docs/commit/c49fa5c400b5799ddc96c7525d41a79e5a1a4c15
