### ISSUE TITLE
comment/code mismatch in server side tracking python code example

### ISSUE THREAD

**Issue by t1m0thy** [mixpanel/docs-legacy#631]
Hello,
If I read correctly, I noticed that the comment string does not appear to match the code here: https://github.com/mixpanel/docs/blob/c2286a4152bf2cf0fd4794ed0aa4c65fe68ebcb7/pages/docs/tracking/how-tos/effective-server-side-tracking.md?plain=1#L210C42-L210C42

I believe the comment may be correct and the code incorrect?  but I am not sure.
Best regards,
Tim

**Comment by ranic** [comment]
Fixed in https://github.com/mixpanel/docs/pull/699
