### ISSUE TITLE
Possibly outdated documentation around identity merge limits

### ISSUE THREAD

**Issue by levrik** [mixpanel/docs-legacy#866]
According to https://docs.mixpanel.com/docs/tracking-methods/sdks/javascript#call-reset-at-logout there's a limit of 500 distinct IDs that can attached to a single user so `reset` shouldn't be called frequently.

Looking at https://docs.mixpanel.com/docs/tracking-methods/id-management/identifying-users#how-does-the-simplified-api-differ-from-the-original-api it tells a different story that this limitation does not exist anymore with the Simplified Merge API?

Is that true? Could the docs of the JS (and a few other SDKs) be updated?

**Comment by levrik** [comment]
@ranic Seeing that you're the most active person from Mixpanel in this repo's issues so hoping to get an answer here.

**Comment by ranic** [comment]
@levrik good catch. It's no longer relevant if you're on Simplified ID Merge. https://github.com/mixpanel/docs/pull/894

**Comment by levrik** [comment]
@ranic Thanks a lot for clarifying this!
