### ISSUE TITLE
Feedback for "Funnels"

### ISSUE THREAD

**Issue by dorothy-koh** [mixpanel/docs-legacy#98]
Referencing https://docs-mixpanel.vercel.app/docs/analysis/reports/funnels#using-conversion-and-drop-off-flows

"Up top, I can see that all of the Funnel's criteria is still maintained." 

This is no longer the case, as the Flows criteria is now on the left side bar. If we were to change this description, we should pair it with a change to the screenshot.

**Comment by ranic** [comment]
https://github.com/mixpanel/docs/commit/d81b8db22b64492ea36875914a7d03e609199865
